name: CI/CD AWS EC2

on:
  push:
    branches:
      - main-ec2

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Reposistory
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      -name: Run Unit test
        run: npm run test
        
      - name: Run ESLint
        run: npm run lint
  deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EC2
      env:
          PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOSTNAME: ${{secrets.EC2_HOST}}
          USER_NAME: ${{secrets.EC2_USER}}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          cd /var/www/storykit &&
          git checkout main &&
          git pull origin main &&
          npm install &&
          npm run build-story &&
          sudo systemctl reload nginx
          '